spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:52703/portfolio
    username: 0tae
    password: portfolio123
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/mysql/db.changelog-master.xml
    enabled: true